######################################################################
# Automatically generated by qmake (3.1) Mon Jun 24 21:45:05 2024
######################################################################

TEMPLATE = app
TARGET = qmake
INCLUDEPATH += .

# Input
SOURCES += qmake.cpp

QT +=widgets gui